### ISSUE TITLE
kivar_cli: primitive test

### ISSUE THREAD

**Issue by honzakutil** [markh-de/KiVar#31]
There is relation between `kivar-cli`outputs: `kivar-cli state` "+" `kivar-cli check` "=" `kivar-cli state --all`. Primitive test of `kivar-cli` can be preformed by running these 3 commands and checking their outputs, if they match the rule listed above.

**Comment by markh-de** [comment]
I think unit testing would be even better than using the CLI.

I'll see when I find time to add this. Until then, yes, using the CLI is an option.

**Comment by markh-de** [comment]
Duplicated by #42.
