### ISSUE TITLE
kivar-cli: state arguments -a -Q should not be used simultaneously

### ISSUE THREAD

**Issue by honzakutil** [markh-de/KiVar#32]
Command `kivar-cli state -a -Q aspect board.kicad_pcb` will outputs only choice selected by `aspect`, not all of them, as instructed by `-a`.  Options `-a` and `-Q aspect` are exclusive and `kivar-cli` should report an error, when these options are used simultaneously.

**Comment by markh-de** [comment]
Thanks for reporting. It's fixed.
