### ISSUE TITLE
KiVar 0.1.2: No rule definitions found - kivar-demo

### ISSUE THREAD

**Issue by rob-bits** [markh-de/KiVar#54]
**Describe the bug**
The KiVar plugin cannot be started in the example kivar-demo project. 

**To Reproduce**
1. install the KiVar from Plugin and Content Manager
2. open kivar-demo.kicad_pro in KiCad 8.0.1 release build
3. in PCB editor open KiVar plugin
**Expected behavior**
Variant selection gui should be appeared.

**Screenshots**
![image](https://github.com/markh-de/KiVar/assets/40227041/80082176-b94c-4f9c-81e7-a8ea7771bbfe)

**Additional context**
Application: KiCad PCB Editor x64 on x64

Version: 8.0.1, release build

Libraries:
	wxWidgets 3.2.4
	FreeType 2.12.1
	HarfBuzz 8.3.0
	FontConfig 2.14.2
	libcurl/8.5.0-DEV Schannel zlib/1.3

Platform: Windows 10 (build 19045), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Mar 15 2024 01:52:47
	wxWidgets: 3.2.4 (wchar_t,wx containers)
	Boost: 1.83.0
	OCC: 7.7.1
	Curl: 8.5.0-DEV
	ngspice: 42
	Compiler: Visual C++ 1936 without C++ ABI

Build settings:

**Comment by markh-de** [comment]
I guess you tried the demo project from the main branch, which matches the software implementation of the main branch (not the 0.1.2 release).

Currently there are no maintenance branches, so please use the demo project found in the matching release source archive: https://github.com/markh-de/KiVar/archive/refs/tags/v0.1.2.zip

I'll try to mention this in the upcoming documentation.
